//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RdfStoreSparqlNamespace {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class storeSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static storeSettings defaultInstance = ((storeSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new storeSettings())));
        
        public static storeSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public int Indexes_max_Changes_For_Rebuild {
            get {
                return ((int)(this["Indexes_max_Changes_For_Rebuild"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://defaltGraph")]
        public string DefualtGraph {
            get {
                return ((string)(this["DefualtGraph"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("spogTable.pac")]
        public string spog_table_file_name {
            get {
                return ((string)(this["spog_table_file_name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:/store/store database/")]
        public string root_dir_path {
            get {
                return ((string)(this["root_dir_path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int max_deletes_for_recreate_table_persent {
            get {
                return ((int)(this["max_deletes_for_recreate_table_persent"]));
            }
        }
    }
}
